version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  config-server:
    image: config-server
    ports:
      - 8088:8088
  service-registry:
    image: service-registry
    depends_on:
      - config-server
    environment:
      - CONFIG_SERVER_URI=http://config-server:8088
    ports:
      - 8761:8761
  api-gateway:
    image: api-gateway
    depends_on:
      - config-server
      - service-registry
    environment:
      - CONFIG_SERVER_URI=http://config-server:8088
      - EUREKA_SERVER_URI=http://service-registry:8761/eureka
    ports:
      - 8099:8099
  customer-service:
    image: customer-service
    depends_on:
      - config-server
      - service-registry
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/customer
      - CONFIG_SERVER_URI=http://config-server:8088
      - EUREKA_SERVER_URI=http://service-registry:8761/eureka
    ports:
      - 8081:8081
  